package net.pslice.musicwriter.program;

import net.pslice.musicwriter.program.music.Note;
import net.pslice.musicwriter.program.music.scale.Scale;
import net.pslice.musicwriter.program.tracks.Track;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class Song {

    /*
     * ================================================
     * Variables, Objects, Sets, Lists and Maps:
     * ================================================
     */

    // The name of the song
    private final String name;
    // The tempo of the song
    private final int tempo;

    // The main key of the song
    private final Note key;
    // The main scale of the song
    private final Scale scale;

    // Set of all tracks generated for the song
    private final Set<Track> tracks;

    // List of all components generated by the song
    private final List<Component> components;





    /*
     * ================================================
     * Initializers:
     * Parameters:
     *      [String] name: The name of the song
     *      [Note] key: The main key of the song
     *      [Scale] scale: The main scale of the song
     *      [Integer] tempo: The tempo of the song
     * ================================================
     */

    public Song(String name, Note key, Scale scale, int tempo)
    {
        this.name = name;
        this.key = key;
        this.scale = scale;
        this.tempo = tempo;

        tracks = new HashSet<>();
        components = new ArrayList<>();
    }





    /*
     * ================================================
     * Getter for the name of the song:
     * ================================================
     */

    public String getName()
    {
        return name;
    }





    /*
     * ================================================
     * Getter for the tempo of the song:
     * ================================================
     */

    public int getTempo()
    {
        return tempo;
    }





    /*
     * ================================================
     * Getter for the key of the song:
     * ================================================
     */

    public Note getKey()
    {
        return key;
    }





    /*
     * ================================================
     * Getter for the scale of the song:
     * ================================================
     */

    public Scale getScale()
    {
        return scale;
    }





    /*
     * ================================================
     * Methods to add and remove tracks from the song:
     * ================================================
     */

    public void addTrack(Track track)
    {
        tracks.add(track);
    }

    public void removeTrack(Track track)
    {
        tracks.remove(track);
    }





    /*
     * ================================================
     * Getter for the tracks in the song:
     * ================================================
     */

    public Set<Track> getTracks()
    {
        return tracks;
    }





    /*
     * ================================================
     * Getter for the list of song components:
     * ================================================
     */

    public List<Component> getComponents()
    {
        return components;
    }
}
